### ISSUE TITLE
`ArweaveApi` does not respect the port in the `gatewayUrl`

### ISSUE THREAD

**Issue by MichaelBuhler** [ardriveapp/arweave-dart#59]
## Symptoms

When running [ArDrive Web](https://github.com/ardriveapp/ardrive-web) with a configured `defaultArweaveGatewayUrl` which contains a non-standard (not 80 nor 443) port number, the app makes outbound calls to the gateway on the wrong port, and fails to discover any drives.

<img width="1002" alt="Screenshot 2024-03-13 at 5 45 44 PM" src="https://github.com/ardriveapp/arweave-dart/assets/9561039/82699d73-1c69-4d7d-b432-cf91822a7158">

## Root Cause

In the `_getSandboxedEndpointUri()` method, a Uri is being constructed without a port:
https://github.com/ardriveapp/arweave-dart/blob/41d590687cecafc316b3c83da20274a29d3e2833/lib/src/api/api.dart#L28-L30

## Fix

Update the templated uri string to include the port number.

**Comment by thiagocarvalhodev** [comment]
Hey @MichaelBuhler, thank you for identifying this issue and providing a fix. The changes are approved. We will include your fix in the upcoming release.
